version: '3'

services:
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    container_name: blackbox_exporter
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    dns:
      - 8.8.8.8
      - 8.8.4.4


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    dns:
      - 8.8.8.8
      - 8.8.4.4